import type {
	Association,
	CreationOptional,
	HasManyAddAssociationMixin,
	HasManyAddAssociationsMixin,
	HasManyCountAssociationsMixin,
	HasManyCreateAssociationMixin,
	HasManyGetAssociationsMixin,
	HasManyHasAssociationMixin,
	HasManyHasAssociationsMixin,
	HasManyRemoveAssociationMixin,
	HasManyRemoveAssociationsMixin,
	HasManySetAssociationsMixin,
	InferAttributes,
	InferCreationAttributes,
	NonAttribute
} from 'sequelize';
import { DataTypes, Model, Sequelize } from 'sequelize';

import JobEvent from './Jobs/JobEvent';
import Job from './Jobs/Job';

export default class Printer extends Model<
	InferAttributes<Printer>,
	InferCreationAttributes<Printer>
> {
	/**
	 * The ID of the printer
	 * (Optional, auto-generated by database at INSERT)
	 */
	declare printerId: CreationOptional<number>;

	/**
	 * The name of the printer
	 */
	declare name: string;

	/**
	 * Description of the printer
	 */
	declare description: string;

	/**
	 * The IP address or hostname, & port of the printer's Moonraker API
	 */
	declare address: string;

	/**
	 * Print Volume
	 */
	declare volume: JSON;
}

export function init(sequelize: Sequelize) {

}
export function associate() {

}